import { StageEnum } from "../api/profile/profile-types.mjs";


export type DB_USER = {
    user_id: number, 
    email: string,
    phone: string,
    verified: Boolean,
    password_hash: string,
    display_name: string, 
    user_role: string, 
    gender:string,
    dob:number,
    zipcode: string,
    stage: StageEnum,
    daily_notification_hour: number,
    partners: number[],
    circles: number[],
    profile_image: string, 
	jwt: string,
};



/* Table Created: 11/6/2022

CREATE TABLE user_table (
	user_id INT PRIMARY KEY generated by default as identity,
	email VARCHAR,
	verified BOOLEAN DEFAULT FALSE,
	password_hash VARCHAR,
	phone VARCHAR,
	display_name VARCHAR,
	user_role user_type DEFAULT 'STUDENT',
	gender gender_type DEFAULT 'MALE',
	dob BIGINT DEFAULT 943941600000,
	zipcode VARCHAR DEFAULT 55060,
	daily_notification_hour INT DEFAULT 8,
	stage stage_type DEFAULT 'GROWING',
	partners INT[],
	circles INT[],	
	profile_image VARCHAR,
	notes VARCHAR
);

*/