import { PrayerRequestTagEnum } from '../../../0-assets/field-sync/input-config-sync/prayer-request-field-config.mjs';

/************************************
* PRAYER REQUEST COMMENTS MOCK DATA *
*************************************/
export const MOCK_PRAYER_REQUEST_COMMENT_MAP:Map<PrayerRequestTagEnum, string[]> = new Map([
    [PrayerRequestTagEnum.SELF, [
        'Praying for strength and guidance as you navigate your personal challenges. May God\'s wisdom and grace empower you to overcome and thrive.',
        'Lifting you up in prayer for strength and perseverance. May God\'s presence provide clarity and encouragement as you face your current challenges.',
        'Asking for God\'s support and guidance in your personal journey. May His wisdom bring you clarity and His strength empower you through difficulties.',
        'Praying for divine assistance as you work through your struggles. May God\'s grace bring you strength, clarity, and the resilience to move forward.',
        'May God\'s guidance and strength be with you as you face personal challenges. Praying for His presence to provide comfort and encouragement.',
        'Lifting you up in prayer for strength and wisdom. May God\'s grace guide you through your struggles and bring you the perseverance you need.',
        'Praying for God\'s support and encouragement in your personal journey. May His presence provide the clarity and strength you need to overcome obstacles.',
        'Asking for divine intervention in your personal struggles. May God\'s grace bring you peace, strength, and the guidance needed to move forward.',
        'Praying for God\'s strength and guidance as you face your challenges. May His wisdom provide clarity and His presence bring comfort and encouragement.',
        'May God\'s grace and strength support you through your personal journey. Praying for clarity and perseverance as you navigate your current difficulties.',
        'Lifting you up in prayer for divine strength and guidance. May God\'s presence bring you the courage and clarity needed to overcome personal challenges.',
        'Praying for God\'s wisdom and strength in your life. May His grace provide comfort and guidance as you work through your current struggles.',
        'Asking for God\'s support as you face personal challenges. May His presence bring clarity, strength, and encouragement to help you through.',
        'Praying for divine assistance and strength in your journey. May God\'s grace provide the clarity and courage needed to overcome your struggles.',
        'May God\'s presence bring comfort and resilience as you face personal challenges. Praying for His strength and guidance to support you through.',
        'Lifting you up in prayer for divine guidance and support. May God\'s strength and grace help you navigate your challenges and find peace.',
        'Praying for God\'s encouragement and wisdom in your personal journey. May His presence provide clarity and strength to help you overcome obstacles.',
        'Asking for divine strength and guidance as you tackle personal challenges. May God\'s grace bring comfort, clarity, and perseverance into your life.',
        'May God\'s grace and support be with you as you face your struggles. Praying for His strength to guide you and His presence to bring comfort.',
        'Lifting you up in prayer for strength and clarity. May God\'s presence bring you the encouragement and wisdom needed to navigate your personal challenges.',
        'Praying for divine guidance and strength as you work through your challenges. May God\'s grace bring you comfort and the perseverance needed to succeed.',
        'Asking for God\'s wisdom and strength to support you through personal difficulties. May His presence provide clarity and encouragement in your journey.',
        'Praying for God\'s grace and strength in your personal journey. May His guidance bring clarity and support as you face your current challenges.',
        'May God\'s presence be a source of comfort and strength as you navigate your personal struggles. Praying for His wisdom and guidance to help you through.',
        'Lifting you up in prayer for divine support and clarity. May God\'s grace provide the strength and encouragement you need to overcome your challenges.',
        'Praying for God\'s wisdom and strength to guide you through your personal journey. May His presence bring comfort and perseverance as you face obstacles.',
    ]],
    [PrayerRequestTagEnum.FAMILY, [
        'Praying for healing and unity within your family. May God\'s love mend broken relationships and bring peace and comfort to everyone involved.',
        'Lifting up prayers for strength and reconciliation in your family. May God\'s guidance restore harmony and bring healing to your loved ones.',
        'Asking God to bless your family with peace and unity. May His presence bring healing and understanding to any areas of conflict or hurt.',
        'Praying for God\'s grace to bring healing and closeness to your family. May His love strengthen bonds and bring comfort to all who need it.',
        'May God\'s healing touch bring restoration and peace to your family. Praying for strength and unity as you work through challenges together.',
        'Lifting up your family in prayer for healing and reconciliation. May God\'s love and guidance bring comfort and restore harmony in your relationships.',
        'Praying for God\'s intervention in your family\'s situation. May His presence bring healing, strength, and renewed connection among your loved ones.',
        'Asking for God\'s blessings on your family. May His love and grace bring healing and unity, making your relationships stronger and more fulfilling.',
        'Praying for peace and healing within your family. May God\'s grace touch each member, bringing comfort and restoration to your relationships.',
        'May God\'s presence bring comfort and healing to your family. Praying for renewed strength and unity as you navigate any challenges together.',
        'Lifting your family up in prayer for restoration and peace. May God\'s guidance help heal any wounds and bring you closer together in love.',
        'Praying for God\'s intervention in your family\'s life. May His love and grace bring healing and strengthen the bonds that unite you.',
        'May God\'s presence bring healing and harmony to your family. Praying for His strength and comfort as you work through challenges and seek reconciliation.',
        'Lifting up prayers for your family\'s healing and unity. May God\'s love and grace bring peace and restoration to all who are affected.',
        'Praying for God\'s blessings on your family. May His grace and strength bring healing, understanding, and renewed closeness among your loved ones.',
        'Asking for God\'s guidance to heal and restore your family relationships. May His presence bring comfort and peace as you work through difficulties.',
        'Praying for God\'s peace and healing in your family. May His love mend broken relationships and bring strength and unity to each member.',
        'Lifting up your family in prayer for divine healing and reconciliation. May God\'s grace and love restore harmony and bring comfort to everyone involved.',
        'May God\'s presence bring peace and restoration to your family. Praying for His strength and guidance as you seek to heal and unite your relationships.',
        'Praying for healing and unity within your family. May God\'s love touch each member, bringing comfort, strength, and renewed connections.',
        'Asking God to bless your family with His grace and healing. May His presence bring comfort and restore any broken relationships among you.',
        'Lifting your family up in prayer for divine intervention. May God\'s love and grace bring healing, strength, and renewed closeness to your relationships.',
        'Praying for God\'s presence to heal and restore your family. May His grace bring peace and unity, helping to mend any divisions or conflicts.',
        'May God\'s love bring healing and reconciliation to your family. Praying for His comfort and strength as you work towards unity and understanding.',
        'Praying for divine guidance and healing for your family. May God\'s presence bring peace and restore relationships, bringing you closer together.',
        'Lifting up your family in prayer for strength and healing. May God\'s grace bring comfort, unity, and renewed connections among your loved ones.',
    ]],
    [PrayerRequestTagEnum.SCHOOL, [
        'Praying for strength and perseverance in your studies. May God grant you the focus and resilience needed to overcome challenges in school.',
        'Lifting you up in prayer for success and wisdom in your academic journey. May God provide the strength and clarity you need for your studies.',
        'Praying for guidance and strength as you face school challenges. May God\'s presence bring clarity and encouragement throughout your academic journey.',
        'May God\'s wisdom and strength be with you as you navigate your school challenges. Praying for perseverance and success in your academic endeavors.',
        'Praying for focus and resilience in your studies. May God provide you with the strength and clarity needed to excel in your academic pursuits.',
        'Lifting you up in prayer for academic success and strength. May God grant you the perseverance and wisdom to overcome any challenges in school.',
        'Praying for divine guidance and strength in your academic journey. May God provide clarity and encouragement as you face school challenges.',
        'May God\'s presence bring comfort and perseverance to your studies. Praying for wisdom and resilience as you navigate academic challenges.',
        'Praying for success and clarity in your academic pursuits. May God grant you strength and focus as you tackle challenges in school.',
        'Lifting you in prayer for wisdom and resilience in your studies. May God provide the guidance and strength needed for academic success.',
        'Praying for God\'s guidance and support in your academic journey. May He provide clarity, strength, and perseverance as you face school challenges.',
        'May God\'s wisdom and strength be with you as you tackle school challenges. Praying for encouragement and success in your studies.',
        'Lifting you up in prayer for academic strength and perseverance. May God grant you clarity and focus in your studies and provide support during challenging times.',
        'Praying for divine guidance and strength in your education. May God\'s presence bring clarity and perseverance as you navigate school challenges.',
        'May God\'s wisdom guide you through your academic journey. Praying for strength, focus, and resilience as you face challenges in school.',
        'Praying for success and clarity in your schoolwork. May God grant you the perseverance and strength needed to overcome academic obstacles.',
        'Lifting you up in prayer for encouragement and resilience in your studies. May God provide the wisdom and strength needed for academic success.',
        'Praying for God\'s presence to bring focus and strength to your studies. May He guide you through challenges and grant you success in your academic pursuits.',
        'May God\'s wisdom and strength support you in your academic challenges. Praying for clarity, perseverance, and success in your studies.',
        'Lifting you up in prayer for divine guidance and strength in your schoolwork. May God provide clarity and encouragement throughout your academic journey.',
        'Praying for perseverance and clarity in your academic journey. May God\'s presence bring you strength and success as you tackle school challenges.',
        'May God\'s support and wisdom guide you in your studies. Praying for focus, resilience, and success as you face academic challenges.',
        'Lifting you in prayer for divine strength and guidance in your schoolwork. May God provide clarity and encouragement during challenging times.',
        'Praying for God\'s presence to bring perseverance and success in your studies. May He grant you the strength and clarity needed for academic achievement.',
        'May God\'s wisdom guide you through school challenges. Praying for focus, strength, and success as you navigate your academic journey.',
        'Lifting you up in prayer for strength and clarity in your studies. May God provide the encouragement and perseverance needed for academic success.',
    ]],
    [PrayerRequestTagEnum.HEALING, [
        'Praying for God\'s healing power to touch your loved ones. May His presence bring comfort, strength, and restoration during this difficult time.',
        'Lifting up prayers for divine healing and comfort. May God\'s presence bring strength and peace to those who are in need of His healing touch.',
        'Praying for God\'s healing grace to cover you and your loved ones. May His presence bring restoration, comfort, and strength during this time.',
        'May God\'s healing hand be upon those who are suffering. Praying for comfort, strength, and divine intervention in this time of need.',
        'Lifting you up in prayer for healing and restoration. May God\'s presence bring comfort and strength as you trust in His power to heal and restore.',
        'Praying for God\'s healing presence to touch your life. May His grace and strength bring comfort and restoration during this challenging time.',
        'May God\'s healing power bring peace and strength to you and your loved ones. Praying for His presence to provide comfort and restoration.',
        'Lifting up prayers for divine healing and support. May God\'s presence bring comfort, strength, and hope to those in need of His healing touch.',
        'Praying for God\'s healing hand to restore and bring peace. May His presence provide comfort and strength as you navigate this difficult time.',
        'May God\'s grace and healing power surround you. Praying for comfort, restoration, and strength as you face these health challenges.',
        'Praying for divine healing and strength. May God\'s presence bring peace, comfort, and restoration to those who are in need of His touch.',
        'Lifting you up in prayer for healing and comfort. May God\'s healing power bring restoration and strength during this challenging time.',
        'May God\'s presence bring peace and healing to your life. Praying for His grace and strength to touch those in need of restoration and comfort.',
        'Praying for God\'s healing touch to bring comfort and strength. May His presence restore and provide peace during this time of need.',
        'Lifting up prayers for divine healing and support. May God\'s presence bring comfort, strength, and restoration to those who are suffering.',
        'Praying for God\'s grace to heal and restore. May His presence bring peace and strength to you and your loved ones during this challenging time.',
        'May God\'s healing power bring comfort and strength. Praying for His presence to provide restoration and peace during this time of need.',
        'Lifting you up in prayer for healing and divine intervention. May God\'s grace bring comfort and strength as you navigate these health challenges.',
        'Praying for God\'s healing touch to restore and bring peace. May His presence provide comfort and strength during this difficult time.',
        'May God\'s healing presence surround you with comfort and peace. Praying for restoration and strength as you face these health challenges.',
        'Lifting you in prayer for divine healing and strength. May God\'s presence bring comfort and restoration during this time of need.',
        'Praying for God\'s grace and healing power. May His presence provide comfort, strength, and restoration during this challenging time.',
        'May God\'s presence bring peace and healing to your life. Praying for His strength and comfort as you face these health challenges.',
        'Lifting up prayers for divine healing and comfort. May God\'s presence restore and bring strength during this time of need and challenge.',
        'Praying for God\'s healing touch to bring peace and strength. May His presence restore and provide comfort as you face these challenges.',
        'May God\'s grace and healing power be with you. Praying for comfort, restoration, and strength as you navigate these health challenges.',
        'Lifting you up in prayer for divine intervention and healing. May God\'s presence bring comfort and strength during this challenging time.',
    ]],
    [PrayerRequestTagEnum.PRAISE, [
        'So grateful for the amazing blessings in your life. May God continue to shower you with His love and grace as you embrace this new chapter.',
        'What a wonderful opportunity to praise God for His incredible provision. May His continued support and guidance fill your heart with joy and peace.',
        'Thanking God for the abundant blessings He\'s poured into your life. May His presence continue to inspire and uplift you as you embark on this new journey.',
        'God\'s grace has been evident in your life, and for that, we praise Him. May His blessings keep flowing and bring you continued joy and encouragement.',
        'Rejoicing with you for the blessings you\'ve received! May God\'s love and support be a constant source of strength and joy in your life.',
        'Praising God for the new blessings and opportunities you\'re experiencing. May His guidance and grace continue to light your path and bring you peace.',
        'What a joy to see God\'s hand at work in your life! May His continued blessings bring you comfort, encouragement, and abundant joy.',
        'Celebrating the wonderful things God is doing in your life. May His love and provision keep you strong and joyful as you move forward.',
        'Thankful for the way God has blessed you. May His presence continue to be a source of strength and joy in your life, guiding you through each new day.',
        'Rejoicing with you over the new blessings and opportunities. May God\'s grace and love continue to uplift and support you in all that you do.',
        'What a blessing to witness God\'s work in your life! May His continued grace and love bring you joy and peace as you embrace this new chapter.',
        'Praising God for His faithfulness and the wonderful blessings He has given. May His presence bring you ongoing comfort and strength in your journey.',
        'So thankful for the ways God has blessed you. May His grace continue to shine upon you and bring joy and encouragement as you face new challenges.',
        'Celebrating the amazing things God is doing for you! May His love and blessings continue to guide and uplift you as you move forward in faith.',
        'Rejoicing in the blessings you\'ve received! May God\'s continued presence bring you peace, strength, and abundant joy as you embark on this new journey.',
        'Praising God for the incredible ways He has provided for you. May His grace and love continue to enrich your life and fill your days with joy.',
        'What a wonderful time to thank God for His blessings. May His ongoing support and love bring you continued encouragement and strength.',
        'Thankful for God\'s amazing provision in your life. May His continued blessings and grace bring you comfort, joy, and the strength to face each day.',
        'Rejoicing in the blessings and opportunities God has given you. May His presence continue to uplift and guide you, bringing peace and joy to your heart.',
        'Praising God for His wonderful work in your life. May His grace and love continue to be a source of strength and encouragement as you navigate new beginnings.',
        'So grateful for God\'s faithful provision. May His continued blessings bring you joy, peace, and the strength to embrace all that lies ahead.',
        'What a joy to see God\'s blessings unfolding in your life. May His love and guidance continue to support and uplift you in every new endeavor.',
        'Rejoicing in the ways God has blessed you! May His grace and presence be a constant source of comfort and strength as you continue on your journey.',
        'Praising God for His continued blessings and grace. May His love bring you joy and encouragement as you embrace new opportunities and challenges.',
        'Thankful for the many ways God has provided for you. May His continued presence bring peace, strength, and joy as you move forward with faith.',
        'Celebrating the wonderful blessings you\'ve received! May God\'s grace and love continue to uplift you and bring you peace and encouragement.',
        'Rejoicing in the new opportunities God has given you. May His continued blessings and support be a source of strength and joy as you face the future.',
        'Praising God for His incredible grace and provision in your life. May His presence bring you ongoing comfort and joy as you navigate new chapters.',
    ]],
    [PrayerRequestTagEnum.GLOBAL, [
        'Praying for peace and safety in troubled regions. May God\'s presence bring comfort, protection, and hope to those affected by global conflicts.',
        'Lifting up prayers for global peace and stability. May God\'s guidance bring comfort and strength to those facing challenges in conflict-affected areas.',
        'Praying for God\'s intervention in global crises. May His peace and protection be with those affected, bringing hope and comfort to troubled regions.',
        'May God\'s presence bring peace and protection to global communities. Praying for comfort and strength for those affected by conflicts and unrest.',
        'Lifting up prayers for peace and stability in troubled regions. May God\'s guidance bring comfort and hope to those facing global challenges.',
        'Praying for divine intervention and peace in conflict-affected areas. May God\'s protection and comfort be with those facing global hardships.',
        'May God\'s presence bring hope and stability to troubled regions. Praying for His peace and protection to surround those affected by global conflicts.',
        'Lifting up prayers for global peace and protection. May God\'s guidance bring comfort and hope to those facing challenges in conflict-affected areas.',
        'Praying for God\'s intervention in global crises. May His presence bring peace, protection, and comfort to those enduring conflicts and unrest.',
        'May God\'s grace and protection be with those affected by global conflicts. Praying for peace, hope, and strength during these challenging times.',
        'Lifting you up in prayer for peace and stability in troubled regions. May God\'s presence bring comfort and protection to those facing global challenges.',
        'Praying for God\'s intervention and peace in conflict zones. May His presence provide comfort, protection, and hope to those in need around the world.',
        'May God\'s presence bring hope and strength to those in conflict-affected areas. Praying for His peace and protection during global crises.',
        'Lifting up prayers for peace and protection in troubled regions. May God\'s grace bring comfort and stability to those facing global challenges.',
        'Praying for divine intervention in global conflicts. May God\'s presence bring peace, hope, and protection to those affected by unrest and turmoil.',
        'May God\'s guidance bring stability and peace to global communities. Praying for comfort and protection for those facing challenges in conflict zones.',
        'Lifting you in prayer for peace and hope in troubled regions. May God\'s presence provide strength and protection during global crises and conflicts.',
        'Praying for God\'s intervention and protection in conflict-affected areas. May His peace and grace bring comfort and stability to those in need.',
        'May God\'s presence bring peace and safety to global communities. Praying for comfort and protection for those facing challenges and unrest.',
        'Lifting up prayers for global peace and stability. May God\'s guidance and protection be with those facing conflicts and hardships around the world.',
        'Praying for divine peace and intervention in troubled regions. May God\'s presence bring hope, protection, and comfort during global crises.',
        'May God\'s guidance bring hope and stability to conflict-affected areas. Praying for His peace and protection for those enduring global challenges.',
        'Lifting you up in prayer for peace and protection in global conflicts. May God\'s presence bring comfort and strength during these challenging times.',
        'Praying for God\'s intervention in global crises. May His presence bring peace, safety, and comfort to those affected by unrest and conflicts.',
        'May God\'s grace and protection be with those facing global challenges. Praying for peace and strength during conflicts and troubled times.',
        'Lifting up prayers for divine intervention and peace. May God\'s presence bring comfort, protection, and hope to those in conflict-affected regions.',
    ]]
]);
